// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nivaes.App.RPC.Client;

#nullable disable

namespace Nivaes.App.RPC.Client.Sources.Database.Migrations
{
    [DbContext(typeof(RpcSyncDatabaseContext))]
    [Migration("20260827124540_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("Nivaes.App.Rpc.Client.SyncSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT")
                        .HasColumnName("Key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Value");

                    b.HasKey("Key");

                    b.ToTable("SyncSetting", (string)null);
                });

            modelBuilder.Entity("Nivaes.App.Rpc.SyncData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("Data");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("EntityType");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeStampTicks")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TimeStampTicks");

                    b.HasKey("Id");

                    b.HasIndex("TimeStampTicks");

                    b.ToTable("SyncData", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
