<Project Sdk="Aspire.AppHost.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	  <TargetFrameworks>$(_CrossCommonTargets)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>52085e4a-f6d8-4773-ba98-2a61b8a3cc26</UserSecretsId>
  </PropertyGroup>

</Project>
