// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Nivaes.App.Rpc.Client.Database
{
    public partial class RpcSyncDatabaseContextModel
    {
        private RpcSyncDatabaseContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("cd996c8f-1271-45da-a53e-227f40f4b2d0"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var syncSetting = SyncSettingEntityType.Create(this);
            var syncData = SyncDataEntityType.Create(this);

            SyncSettingEntityType.CreateAnnotations(syncSetting);
            SyncDataEntityType.CreateAnnotations(syncData);

            AddAnnotation("ProductVersion", "10.0.11");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var syncSetting = FindEntityType("Nivaes.App.Rpc.Client.SyncSetting")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            syncSetting.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var nivaesAppRpcClientSyncSettingTableBase = new TableBase("Nivaes.App.Rpc.Client.SyncSetting", null, relationalModel);
            var keyColumnBase = new ColumnBase<ColumnMappingBase>("Key", "TEXT", nivaesAppRpcClientSyncSettingTableBase);
            nivaesAppRpcClientSyncSettingTableBase.Columns.Add("Key", keyColumnBase);
            var valueColumnBase = new ColumnBase<ColumnMappingBase>("Value", "TEXT", nivaesAppRpcClientSyncSettingTableBase);
            nivaesAppRpcClientSyncSettingTableBase.Columns.Add("Value", valueColumnBase);
            relationalModel.DefaultTables.Add("Nivaes.App.Rpc.Client.SyncSetting", nivaesAppRpcClientSyncSettingTableBase);
            var nivaesAppRpcClientSyncSettingMappingBase = new TableMappingBase<ColumnMappingBase>(syncSetting, nivaesAppRpcClientSyncSettingTableBase, null);
            nivaesAppRpcClientSyncSettingTableBase.AddTypeMapping(nivaesAppRpcClientSyncSettingMappingBase, false);
            defaultTableMappings.Add(nivaesAppRpcClientSyncSettingMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)keyColumnBase, syncSetting.FindProperty("Key")!, nivaesAppRpcClientSyncSettingMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)valueColumnBase, syncSetting.FindProperty("Value")!, nivaesAppRpcClientSyncSettingMappingBase);

            var tableMappings = new List<TableMapping>();
            syncSetting.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var syncSettingTable = new Table("SyncSetting", null, relationalModel);
            var keyColumn = new Column("Key", "TEXT", syncSettingTable);
            syncSettingTable.Columns.Add("Key", keyColumn);
            keyColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(keyColumn);
            var valueColumn = new Column("Value", "TEXT", syncSettingTable);
            syncSettingTable.Columns.Add("Value", valueColumn);
            valueColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(valueColumn);
            relationalModel.Tables.Add(("SyncSetting", null), syncSettingTable);
            var syncSettingTableMapping = new TableMapping(syncSetting, syncSettingTable, null);
            syncSettingTable.AddTypeMapping(syncSettingTableMapping, false);
            tableMappings.Add(syncSettingTableMapping);
            RelationalModel.CreateColumnMapping(keyColumn, syncSetting.FindProperty("Key")!, syncSettingTableMapping);
            RelationalModel.CreateColumnMapping(valueColumn, syncSetting.FindProperty("Value")!, syncSettingTableMapping);
            var pK_SyncSetting = new UniqueConstraint("PK_SyncSetting", syncSettingTable, new[] { keyColumn });
            syncSettingTable.PrimaryKey = pK_SyncSetting;
            pK_SyncSetting.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<string>(pK_SyncSetting));
            var pK_SyncSettingKey = RelationalModel.GetKey(this,
                "Nivaes.App.Rpc.Client.SyncSetting",
                new[] { "Key" });
            pK_SyncSetting.MappedKeys.Add(pK_SyncSettingKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_SyncSettingKey).Add(pK_SyncSetting);
            syncSettingTable.UniqueConstraints.Add("PK_SyncSetting", pK_SyncSetting);

            var syncData = FindEntityType("Nivaes.App.Rpc.SyncData")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            syncData.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var nivaesAppRpcSyncDataTableBase = new TableBase("Nivaes.App.Rpc.SyncData", null, relationalModel);
            var dataColumnBase = new ColumnBase<ColumnMappingBase>("Data", "BLOB", nivaesAppRpcSyncDataTableBase);
            nivaesAppRpcSyncDataTableBase.Columns.Add("Data", dataColumnBase);
            var entityTypeColumnBase = new ColumnBase<ColumnMappingBase>("EntityType", "TEXT", nivaesAppRpcSyncDataTableBase);
            nivaesAppRpcSyncDataTableBase.Columns.Add("EntityType", entityTypeColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "TEXT", nivaesAppRpcSyncDataTableBase);
            nivaesAppRpcSyncDataTableBase.Columns.Add("Id", idColumnBase);
            var timeStampColumnBase = new ColumnBase<ColumnMappingBase>("TimeStamp", "TEXT", nivaesAppRpcSyncDataTableBase);
            nivaesAppRpcSyncDataTableBase.Columns.Add("TimeStamp", timeStampColumnBase);
            var timeStampTicksColumnBase = new ColumnBase<ColumnMappingBase>("TimeStampTicks", "INTEGER", nivaesAppRpcSyncDataTableBase);
            nivaesAppRpcSyncDataTableBase.Columns.Add("TimeStampTicks", timeStampTicksColumnBase);
            relationalModel.DefaultTables.Add("Nivaes.App.Rpc.SyncData", nivaesAppRpcSyncDataTableBase);
            var nivaesAppRpcSyncDataMappingBase = new TableMappingBase<ColumnMappingBase>(syncData, nivaesAppRpcSyncDataTableBase, null);
            nivaesAppRpcSyncDataTableBase.AddTypeMapping(nivaesAppRpcSyncDataMappingBase, false);
            defaultTableMappings0.Add(nivaesAppRpcSyncDataMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, syncData.FindProperty("Id")!, nivaesAppRpcSyncDataMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)dataColumnBase, syncData.FindProperty("Data")!, nivaesAppRpcSyncDataMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityTypeColumnBase, syncData.FindProperty("EntityType")!, nivaesAppRpcSyncDataMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)timeStampColumnBase, syncData.FindProperty("TimeStamp")!, nivaesAppRpcSyncDataMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)timeStampTicksColumnBase, syncData.FindProperty("TimeStampTicks")!, nivaesAppRpcSyncDataMappingBase);

            var tableMappings0 = new List<TableMapping>();
            syncData.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var syncDataTable = new Table("SyncData", null, relationalModel);
            var idColumn = new Column("Id", "TEXT", syncDataTable);
            syncDataTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn);
            var dataColumn = new Column("Data", "BLOB", syncDataTable);
            syncDataTable.Columns.Add("Data", dataColumn);
            dataColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<byte[]>(dataColumn);
            var entityTypeColumn = new Column("EntityType", "TEXT", syncDataTable);
            syncDataTable.Columns.Add("EntityType", entityTypeColumn);
            entityTypeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(entityTypeColumn);
            var timeStampColumn = new Column("TimeStamp", "TEXT", syncDataTable);
            syncDataTable.Columns.Add("TimeStamp", timeStampColumn);
            timeStampColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(timeStampColumn);
            var timeStampTicksColumn = new Column("TimeStampTicks", "INTEGER", syncDataTable);
            syncDataTable.Columns.Add("TimeStampTicks", timeStampTicksColumn);
            timeStampTicksColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(timeStampTicksColumn);
            relationalModel.Tables.Add(("SyncData", null), syncDataTable);
            var syncDataTableMapping = new TableMapping(syncData, syncDataTable, null);
            syncDataTable.AddTypeMapping(syncDataTableMapping, false);
            tableMappings0.Add(syncDataTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, syncData.FindProperty("Id")!, syncDataTableMapping);
            RelationalModel.CreateColumnMapping(dataColumn, syncData.FindProperty("Data")!, syncDataTableMapping);
            RelationalModel.CreateColumnMapping(entityTypeColumn, syncData.FindProperty("EntityType")!, syncDataTableMapping);
            RelationalModel.CreateColumnMapping(timeStampColumn, syncData.FindProperty("TimeStamp")!, syncDataTableMapping);
            RelationalModel.CreateColumnMapping(timeStampTicksColumn, syncData.FindProperty("TimeStampTicks")!, syncDataTableMapping);
            var pK_SyncData = new UniqueConstraint("PK_SyncData", syncDataTable, new[] { idColumn });
            syncDataTable.PrimaryKey = pK_SyncData;
            pK_SyncData.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_SyncData));
            var pK_SyncDataKey = RelationalModel.GetKey(this,
                "Nivaes.App.Rpc.SyncData",
                new[] { "Id" });
            pK_SyncData.MappedKeys.Add(pK_SyncDataKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_SyncDataKey).Add(pK_SyncData);
            syncDataTable.UniqueConstraints.Add("PK_SyncData", pK_SyncData);
            var iX_SyncData_TimeStampTicks = new TableIndex(
            "IX_SyncData_TimeStampTicks", syncDataTable, new[] { timeStampTicksColumn }, false);
            iX_SyncData_TimeStampTicks.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<long>(iX_SyncData_TimeStampTicks));
            var iX_SyncData_TimeStampTicksIx = RelationalModel.GetIndex(this,
                "Nivaes.App.Rpc.SyncData",
                new[] { "TimeStampTicks" });
            iX_SyncData_TimeStampTicks.MappedIndexes.Add(iX_SyncData_TimeStampTicksIx);
            RelationalModel.GetOrCreateTableIndexes(iX_SyncData_TimeStampTicksIx).Add(iX_SyncData_TimeStampTicks);
            syncDataTable.Indexes.Add("IX_SyncData_TimeStampTicks", iX_SyncData_TimeStampTicks);
            return relationalModel.MakeReadOnly();
        }
    }
}
