// <auto-generated />

using Nivaes.App.Rpc;
using Nivaes.App.RPC.Client;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Infrastructure.Internal;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Query;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;

#pragma warning disable EF9100 // Precompiled query is experimental

namespace Microsoft.EntityFrameworkCore.GeneratedInterceptors
{
    file static class EntityFrameworkCoreInterceptors
    {
        #region Query1

        [InterceptsLocation(@"C:\Apl\NivLib\Nivaes.App.RPC\Sources\Nivaes.App.Rpc.Client\Sources\RpcSyncDataWorker.cs", 47, 14)]
        public static global::System.Linq.IQueryable<TSource> Query1_Take1<TSource>(this global::System.Linq.IQueryable<TSource> source, global::System.Int32 count)
        {
            var precompiledQueryContext = new PrecompiledQueryContext<TSource>(((IInfrastructure<DbContext>)source).Instance);
            var queryContext = precompiledQueryContext.QueryContext;
            queryContext.Parameters.Add("p", count);
            return precompiledQueryContext;
        }

        [InterceptsLocation(@"C:\Apl\NivLib\Nivaes.App.RPC\Sources\Nivaes.App.Rpc.Client\Sources\RpcSyncDataWorker.cs", 48, 14)]
        public static global::System.Threading.Tasks.Task<global::System.Collections.Generic.List<TSource>> Query1_ToListAsync2<TSource>(this global::System.Linq.IQueryable<TSource> source, global::System.Threading.CancellationToken cancellationToken)
        {
            var precompiledQueryContext = (PrecompiledQueryContext<TSource>)source;
            var queryContext = precompiledQueryContext.QueryContext;
            Query1_Executor ??= Query1_GenerateExecutor(precompiledQueryContext.DbContext, precompiledQueryContext.QueryContext);
            var queryingEnumerable = ((Func<QueryContext, IAsyncEnumerable<TSource>>)(Query1_Executor))(queryContext);
            var asyncQueryingEnumerable = new PrecompiledQueryableAsyncEnumerableAdapter<TSource>(queryingEnumerable);
            return asyncQueryingEnumerable.ToListAsync(cancellationToken);
        }

        private static object Query1_GenerateExecutor(DbContext dbContext, QueryContext queryContext)
        {
            var relationalModel = dbContext.Model.GetRelationalModel();
            var relationalTypeMappingSource = dbContext.GetService<IRelationalTypeMappingSource>();
            var materializerLiftableConstantContext = new RelationalMaterializerLiftableConstantContext(
                dbContext.GetService<ShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalShapedQueryCompilingExpressionVisitorDependencies>(),
                dbContext.GetService<RelationalCommandBuilderDependencies>());
            var relationalCommandTemplate = ((IRelationalCommandTemplate)(new RelationalCommand(materializerLiftableConstantContext.CommandBuilderDependencies, "SELECT \"s\".\"Id\", \"s\".\"Data\", \"s\".\"EntityType\", \"s\".\"TimeStamp\", \"s\".\"TimeStampTicks\"\r\nFROM \"SyncData\" AS \"s\"\r\nLIMIT @p", "SELECT \"s\".\"Id\", \"s\".\"Data\", \"s\".\"EntityType\", \"s\".\"TimeStamp\", \"s\".\"TimeStampTicks\"\r\nFROM \"SyncData\" AS \"s\"\r\nLIMIT @p", new IRelationalParameter[] { new TypeMappedRelationalParameter("p", "@p", relationalTypeMappingSource.FindMapping(typeof(int), "INTEGER", false, false, (int? )(null), false, false, (int? )(null), (int? )(null)), false, ParameterDirection.Input) })));
            var emptyValueBuffer = ValueBuffer.Empty;
            var syncDataEntityType = materializerLiftableConstantContext.Dependencies.Model.FindEntityType("Nivaes.App.Rpc.SyncData");
            var key = syncDataEntityType.FindPrimaryKey();
            var emptySnapshot = Snapshot.Empty;
            var syncDataEntityType0 = ((RuntimeEntityType)syncDataEntityType);
            return IAsyncEnumerable<SyncData> (QueryContext queryContext) => SingleQueryingEnumerable.Create(((RelationalQueryContext)queryContext), IRelationalCommandTemplate (Dictionary<string, object> parameters) => relationalCommandTemplate, (ReaderColumn[])(null), SyncData (QueryContext queryContext, DbDataReader dataReader, ResultContext resultContext, SingleQueryResultCoordinator resultCoordinator) =>
{
    IEntityType entityType1 = default(IEntityType);
    bool hasNullKey1 = default(bool);
    var materializationContext1 = new MaterializationContext(in emptyValueBuffer, queryContext.Context);
    var instance1 = default(SyncData);
    var entry1 = queryContext.TryGetEntry(key, new object[] { ((object)(dataReader.GetGuid(0))) }, true, out hasNullKey1);
    if (!hasNullKey1)
    {
        if (entry1 != default(InternalEntityEntry))
        {
            entityType1 = entry1.EntityType;
            instance1 = ((SyncData)(entry1.Entity));
        }
        else
        {
            var shadowSnapshot1 = emptySnapshot;
            entityType1 = syncDataEntityType;
            if (entityType1 == syncDataEntityType)
            {
                var instance = new SyncData();
                UnsafeAccessor_Nivaes_App_Rpc_SyncData_Id_Set(instance) = dataReader.GetGuid(0);
                UnsafeAccessor_Nivaes_App_Rpc_SyncData_Data_Set(instance) = dataReader.GetFieldValue<byte[]>(1);
                UnsafeAccessor_Nivaes_App_Rpc_SyncData_EntityType_Set(instance) = dataReader.GetString(2);
                instance.TimeStamp = dataReader.GetDateTime(3);
                UnsafeAccessor_Nivaes_App_Rpc_SyncData_TimeStampTicks_Set(instance) = dataReader.GetInt64(4);
                if (instance is IInjectableService)
                {
                    ((IInjectableService)instance).Injected(materializationContext1.Context, instance, QueryTrackingBehavior.TrackAll, syncDataEntityType0);
                }

                instance1 = instance;
            }
            else
            {
                instance1 = default(SyncData);
            }

            entry1 = (entityType1 == default(IEntityType) ? default(InternalEntityEntry) : queryContext.StartTracking(entityType1, instance1, in shadowSnapshot1));
        }
    }

    var entity = instance1;
    return entity;
}, typeof(RpcSyncDatabaseContext), false, false, true);
        }

        private static object Query1_Executor;

        #endregion Query1
        #region Unsafe accessors
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
private static extern ref Guid UnsafeAccessor_Nivaes_App_Rpc_SyncData_Id_Set(SyncData instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Data>k__BackingField")]
private static extern ref byte[] UnsafeAccessor_Nivaes_App_Rpc_SyncData_Data_Set(SyncData instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityType>k__BackingField")]
private static extern ref string UnsafeAccessor_Nivaes_App_Rpc_SyncData_EntityType_Set(SyncData instance);
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TimeStampTicks>k__BackingField")]
private static extern ref long UnsafeAccessor_Nivaes_App_Rpc_SyncData_TimeStampTicks_Set(SyncData instance);
        #endregion Unsafe accessors
    }
}

namespace System.Runtime.CompilerServices
{
    [AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
    file sealed class InterceptsLocationAttribute : Attribute
    {
        public InterceptsLocationAttribute(string filePath, int line, int column) { }
    }
}
