// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Nivaes.App.RPC.Client.Database
{
    public partial class RpcSyncDatabaseContextModel
    {
        private RpcSyncDatabaseContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("99bc625f-a35e-4970-a0b3-0f9f5cff4268"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var syncData = SyncDataEntityType.Create(this);

            SyncDataEntityType.CreateAnnotations(syncData);

            AddAnnotation("ProductVersion", "10.0.11");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var syncData = FindEntityType("Nivaes.App.Rpc.SyncData")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            syncData.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var nivaesAppRpcSyncDataTableBase = new TableBase("Nivaes.App.Rpc.SyncData", null, relationalModel);
            var dataColumnBase = new ColumnBase<ColumnMappingBase>("Data", "BLOB", nivaesAppRpcSyncDataTableBase);
            nivaesAppRpcSyncDataTableBase.Columns.Add("Data", dataColumnBase);
            var entityTypeColumnBase = new ColumnBase<ColumnMappingBase>("EntityType", "TEXT", nivaesAppRpcSyncDataTableBase);
            nivaesAppRpcSyncDataTableBase.Columns.Add("EntityType", entityTypeColumnBase);
            var idColumnBase = new ColumnBase<ColumnMappingBase>("Id", "TEXT", nivaesAppRpcSyncDataTableBase);
            nivaesAppRpcSyncDataTableBase.Columns.Add("Id", idColumnBase);
            var timeStampColumnBase = new ColumnBase<ColumnMappingBase>("TimeStamp", "TEXT", nivaesAppRpcSyncDataTableBase);
            nivaesAppRpcSyncDataTableBase.Columns.Add("TimeStamp", timeStampColumnBase);
            var timeStampTicksColumnBase = new ColumnBase<ColumnMappingBase>("TimeStampTicks", "INTEGER", nivaesAppRpcSyncDataTableBase);
            nivaesAppRpcSyncDataTableBase.Columns.Add("TimeStampTicks", timeStampTicksColumnBase);
            relationalModel.DefaultTables.Add("Nivaes.App.Rpc.SyncData", nivaesAppRpcSyncDataTableBase);
            var nivaesAppRpcSyncDataMappingBase = new TableMappingBase<ColumnMappingBase>(syncData, nivaesAppRpcSyncDataTableBase, null);
            nivaesAppRpcSyncDataTableBase.AddTypeMapping(nivaesAppRpcSyncDataMappingBase, false);
            defaultTableMappings.Add(nivaesAppRpcSyncDataMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idColumnBase, syncData.FindProperty("Id")!, nivaesAppRpcSyncDataMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)dataColumnBase, syncData.FindProperty("Data")!, nivaesAppRpcSyncDataMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)entityTypeColumnBase, syncData.FindProperty("EntityType")!, nivaesAppRpcSyncDataMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)timeStampColumnBase, syncData.FindProperty("TimeStamp")!, nivaesAppRpcSyncDataMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)timeStampTicksColumnBase, syncData.FindProperty("TimeStampTicks")!, nivaesAppRpcSyncDataMappingBase);

            var tableMappings = new List<TableMapping>();
            syncData.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var syncDataTable = new Table("SyncData", null, relationalModel);
            var idColumn = new Column("Id", "TEXT", syncDataTable);
            syncDataTable.Columns.Add("Id", idColumn);
            idColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idColumn);
            var dataColumn = new Column("Data", "BLOB", syncDataTable);
            syncDataTable.Columns.Add("Data", dataColumn);
            dataColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<byte[]>(dataColumn);
            var entityTypeColumn = new Column("EntityType", "TEXT", syncDataTable);
            syncDataTable.Columns.Add("EntityType", entityTypeColumn);
            entityTypeColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(entityTypeColumn);
            var timeStampColumn = new Column("TimeStamp", "TEXT", syncDataTable);
            syncDataTable.Columns.Add("TimeStamp", timeStampColumn);
            timeStampColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(timeStampColumn);
            var timeStampTicksColumn = new Column("TimeStampTicks", "INTEGER", syncDataTable);
            syncDataTable.Columns.Add("TimeStampTicks", timeStampTicksColumn);
            timeStampTicksColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(timeStampTicksColumn);
            relationalModel.Tables.Add(("SyncData", null), syncDataTable);
            var syncDataTableMapping = new TableMapping(syncData, syncDataTable, null);
            syncDataTable.AddTypeMapping(syncDataTableMapping, false);
            tableMappings.Add(syncDataTableMapping);
            RelationalModel.CreateColumnMapping(idColumn, syncData.FindProperty("Id")!, syncDataTableMapping);
            RelationalModel.CreateColumnMapping(dataColumn, syncData.FindProperty("Data")!, syncDataTableMapping);
            RelationalModel.CreateColumnMapping(entityTypeColumn, syncData.FindProperty("EntityType")!, syncDataTableMapping);
            RelationalModel.CreateColumnMapping(timeStampColumn, syncData.FindProperty("TimeStamp")!, syncDataTableMapping);
            RelationalModel.CreateColumnMapping(timeStampTicksColumn, syncData.FindProperty("TimeStampTicks")!, syncDataTableMapping);
            var pK_SyncData = new UniqueConstraint("PK_SyncData", syncDataTable, new[] { idColumn });
            syncDataTable.PrimaryKey = pK_SyncData;
            pK_SyncData.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_SyncData));
            var pK_SyncDataKey = RelationalModel.GetKey(this,
                "Nivaes.App.Rpc.SyncData",
                new[] { "Id" });
            pK_SyncData.MappedKeys.Add(pK_SyncDataKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_SyncDataKey).Add(pK_SyncData);
            syncDataTable.UniqueConstraints.Add("PK_SyncData", pK_SyncData);
            var iX_SyncData_TimeStampTicks = new TableIndex(
            "IX_SyncData_TimeStampTicks", syncDataTable, new[] { timeStampTicksColumn }, false);
            iX_SyncData_TimeStampTicks.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<long>(iX_SyncData_TimeStampTicks));
            var iX_SyncData_TimeStampTicksIx = RelationalModel.GetIndex(this,
                "Nivaes.App.Rpc.SyncData",
                new[] { "TimeStampTicks" });
            iX_SyncData_TimeStampTicks.MappedIndexes.Add(iX_SyncData_TimeStampTicksIx);
            RelationalModel.GetOrCreateTableIndexes(iX_SyncData_TimeStampTicksIx).Add(iX_SyncData_TimeStampTicks);
            syncDataTable.Indexes.Add("IX_SyncData_TimeStampTicks", iX_SyncData_TimeStampTicks);
            return relationalModel.MakeReadOnly();
        }
    }
}
