// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Nivaes.App.RPC.Client;
using Nivaes.App.RPC.Client.Database;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(RpcSyncDatabaseContext), typeof(RpcSyncDatabaseContextModel))]
