// <auto-generated />
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using Nivaes.App.Rpc;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Nivaes.App.RPC.Client.Database
{
    [EntityFrameworkInternal]
    public partial class SyncDataEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Nivaes.App.Rpc.SyncData",
                typeof(SyncData),
                baseEntityType,
                propertyCount: 5,
                unnamedIndexCount: 1,
                keyCount: 1);

            var id = runtimeEntityType.AddProperty(
                "Id",
                typeof(Guid),
                propertyInfo: typeof(SyncData).GetProperty("Id", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncData).GetField("<Id>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetGetter(
                Guid (SyncData instance) => SyncDataUnsafeAccessors.Id(instance),
                bool (SyncData instance) => SyncDataUnsafeAccessors.Id(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            id.SetSetter(
                SyncData (SyncData instance, Guid value) =>
                {
                    SyncDataUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetMaterializationSetter(
                SyncData (SyncData instance, Guid value) =>
                {
                    SyncDataUnsafeAccessors.Id(instance) = value;
                    return instance;
                });
            id.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && SyncDataUnsafeAccessors.Id(((SyncData)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : SyncDataUnsafeAccessors.Id(((SyncData)(entry.Entity))))),
                Guid (IInternalEntry entry) => SyncDataUnsafeAccessors.Id(((SyncData)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(id, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(id, 0));
            id.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            id.TypeMapping = SqliteGuidTypeMapping.Default;
            id.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(id));

            var data = runtimeEntityType.AddProperty(
                "Data",
                typeof(byte[]),
                propertyInfo: typeof(SyncData).GetProperty("Data", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncData).GetField("<Data>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            data.SetGetter(
                byte[] (SyncData instance) => SyncDataUnsafeAccessors.Data(instance),
                bool (SyncData instance) => SyncDataUnsafeAccessors.Data(instance) == null);
            data.SetSetter(
                SyncData (SyncData instance, byte[] value) =>
                {
                    SyncDataUnsafeAccessors.Data(instance) = value;
                    return instance;
                });
            data.SetMaterializationSetter(
                SyncData (SyncData instance, byte[] value) =>
                {
                    SyncDataUnsafeAccessors.Data(instance) = value;
                    return instance;
                });
            data.SetAccessors(
                byte[] (IInternalEntry entry) => SyncDataUnsafeAccessors.Data(((SyncData)(entry.Entity))),
                byte[] (IInternalEntry entry) => SyncDataUnsafeAccessors.Data(((SyncData)(entry.Entity))),
                byte[] (IInternalEntry entry) => entry.ReadOriginalValue<byte[]>(data, 1),
                byte[] (IInternalEntry entry) => entry.GetCurrentValue<byte[]>(data));
            data.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            data.TypeMapping = SqliteByteArrayTypeMapping.Default.Clone(
                comparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => ((object)v).GetHashCode(),
                    byte[] (byte[] v) => v),
                keyComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()),
                providerValueComparer: new ValueComparer<byte[]>(
                    bool (byte[] v1, byte[] v2) => StructuralComparisons.StructuralEqualityComparer.Equals(((object)v1), ((object)v2)),
                    int (byte[] v) => StructuralComparisons.StructuralEqualityComparer.GetHashCode(((object)v)),
                    byte[] (byte[] source) => source.ToArray()));
            data.AddAnnotation("Relational:ColumnName", "Data");

            var entityType = runtimeEntityType.AddProperty(
                "EntityType",
                typeof(string),
                propertyInfo: typeof(SyncData).GetProperty("EntityType", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncData).GetField("<EntityType>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            entityType.SetGetter(
                string (SyncData instance) => SyncDataUnsafeAccessors.EntityType(instance),
                bool (SyncData instance) => SyncDataUnsafeAccessors.EntityType(instance) == null);
            entityType.SetSetter(
                SyncData (SyncData instance, string value) =>
                {
                    SyncDataUnsafeAccessors.EntityType(instance) = value;
                    return instance;
                });
            entityType.SetMaterializationSetter(
                SyncData (SyncData instance, string value) =>
                {
                    SyncDataUnsafeAccessors.EntityType(instance) = value;
                    return instance;
                });
            entityType.SetAccessors(
                string (IInternalEntry entry) => SyncDataUnsafeAccessors.EntityType(((SyncData)(entry.Entity))),
                string (IInternalEntry entry) => SyncDataUnsafeAccessors.EntityType(((SyncData)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(entityType, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(entityType));
            entityType.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            entityType.TypeMapping = SqliteStringTypeMapping.Default;
            entityType.AddAnnotation("Relational:ColumnName", "EntityType");

            var timeStamp = runtimeEntityType.AddProperty(
                "TimeStamp",
                typeof(DateTime),
                propertyInfo: typeof(SyncData).GetProperty("TimeStamp", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            timeStamp.SetGetter(
                DateTime (SyncData instance) => instance.TimeStamp,
                bool (SyncData instance) => instance.TimeStamp == default(DateTime));
            timeStamp.SetSetter(
                SyncData (SyncData instance, DateTime value) =>
                {
                    instance.TimeStamp = value;
                    return instance;
                });
            timeStamp.SetMaterializationSetter(
                SyncData (SyncData instance, DateTime value) =>
                {
                    instance.TimeStamp = value;
                    return instance;
                });
            timeStamp.SetAccessors(
                DateTime (IInternalEntry entry) => ((SyncData)(entry.Entity)).TimeStamp,
                DateTime (IInternalEntry entry) => ((SyncData)(entry.Entity)).TimeStamp,
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(timeStamp, 3),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(timeStamp));
            timeStamp.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            timeStamp.TypeMapping = SqliteDateTimeTypeMapping.Default;

            var timeStampTicks = runtimeEntityType.AddProperty(
                "TimeStampTicks",
                typeof(long),
                propertyInfo: typeof(SyncData).GetProperty("TimeStampTicks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncData).GetField("<TimeStampTicks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            timeStampTicks.SetGetter(
                long (SyncData instance) => SyncDataUnsafeAccessors.TimeStampTicks(instance),
                bool (SyncData instance) => SyncDataUnsafeAccessors.TimeStampTicks(instance) == 0L);
            timeStampTicks.SetSetter(
                SyncData (SyncData instance, long value) =>
                {
                    SyncDataUnsafeAccessors.TimeStampTicks(instance) = value;
                    return instance;
                });
            timeStampTicks.SetMaterializationSetter(
                SyncData (SyncData instance, long value) =>
                {
                    SyncDataUnsafeAccessors.TimeStampTicks(instance) = value;
                    return instance;
                });
            timeStampTicks.SetAccessors(
                long (IInternalEntry entry) => SyncDataUnsafeAccessors.TimeStampTicks(((SyncData)(entry.Entity))),
                long (IInternalEntry entry) => SyncDataUnsafeAccessors.TimeStampTicks(((SyncData)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(timeStampTicks, 4),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(timeStampTicks));
            timeStampTicks.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            timeStampTicks.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            timeStampTicks.AddAnnotation("Relational:ColumnName", "TimeStampTicks");

            var key = runtimeEntityType.AddKey(
                new[] { id });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { timeStampTicks });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var id = runtimeEntityType.FindProperty("Id");
            var data = runtimeEntityType.FindProperty("Data");
            var entityType = runtimeEntityType.FindProperty("EntityType");
            var timeStamp = runtimeEntityType.FindProperty("TimeStamp");
            var timeStampTicks = runtimeEntityType.FindProperty("TimeStampTicks");
            var key = runtimeEntityType.FindKey(new[] { id });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((SyncData)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, byte[], string, DateTime, long>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)), (source.GetCurrentValue<byte[]>(data) == null ? null : ((ValueComparer<byte[]>)(((IProperty)data).GetValueComparer())).Snapshot(source.GetCurrentValue<byte[]>(data))), (source.GetCurrentValue<string>(entityType) == null ? null : ((ValueComparer<string>)(((IProperty)entityType).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(entityType))), ((ValueComparer<DateTime>)(((IProperty)timeStamp).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(timeStamp)), ((ValueComparer<long>)(((IProperty)timeStampTicks).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(timeStampTicks)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((SyncData)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)id).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(id)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 5,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 5,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "SyncData");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
