// <auto-generated />
using System;
using System.Runtime.CompilerServices;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Nivaes.App.Rpc.Client.Database
{
    public static class SyncDataUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Id>k__BackingField")]
        public static extern ref Guid Id(SyncData @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Data>k__BackingField")]
        public static extern ref byte[] Data(SyncData @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<EntityType>k__BackingField")]
        public static extern ref string EntityType(SyncData @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TimeStampTicks>k__BackingField")]
        public static extern ref long TimeStampTicks(SyncData @this);
    }
}
