// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Nivaes.App.Rpc.Client.Database
{
    [EntityFrameworkInternal]
    public partial class SyncSettingEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Nivaes.App.Rpc.Client.SyncSetting",
                typeof(SyncSetting),
                baseEntityType,
                propertyCount: 2,
                keyCount: 1);

            var key = runtimeEntityType.AddProperty(
                "Key",
                typeof(string),
                propertyInfo: typeof(SyncSetting).GetProperty("Key", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncSetting).GetField("<Key>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                afterSaveBehavior: PropertySaveBehavior.Throw);
            key.SetGetter(
                string (SyncSetting instance) => SyncSettingUnsafeAccessors.Key(instance),
                bool (SyncSetting instance) => SyncSettingUnsafeAccessors.Key(instance) == null);
            key.SetSetter(
                SyncSetting (SyncSetting instance, string value) =>
                {
                    SyncSettingUnsafeAccessors.Key(instance) = value;
                    return instance;
                });
            key.SetMaterializationSetter(
                SyncSetting (SyncSetting instance, string value) =>
                {
                    SyncSettingUnsafeAccessors.Key(instance) = value;
                    return instance;
                });
            key.SetAccessors(
                string (IInternalEntry entry) => SyncSettingUnsafeAccessors.Key(((SyncSetting)(entry.Entity))),
                string (IInternalEntry entry) => SyncSettingUnsafeAccessors.Key(((SyncSetting)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(key, 0),
                string (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<string>(key, 0));
            key.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: -1);
            key.TypeMapping = SqliteStringTypeMapping.Default;
            key.SetCurrentValueComparer(new EntryCurrentValueComparer<string>(key));
            key.AddAnnotation("Relational:ColumnName", "Key");

            var value = runtimeEntityType.AddProperty(
                "Value",
                typeof(string),
                propertyInfo: typeof(SyncSetting).GetProperty("Value", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(SyncSetting).GetField("<Value>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            value.SetGetter(
                string (SyncSetting instance) => SyncSettingUnsafeAccessors.Value(instance),
                bool (SyncSetting instance) => SyncSettingUnsafeAccessors.Value(instance) == null);
            value.SetSetter(
                SyncSetting (SyncSetting instance, string value) =>
                {
                    SyncSettingUnsafeAccessors.Value(instance) = value;
                    return instance;
                });
            value.SetMaterializationSetter(
                SyncSetting (SyncSetting instance, string value) =>
                {
                    SyncSettingUnsafeAccessors.Value(instance) = value;
                    return instance;
                });
            value.SetAccessors(
                string (IInternalEntry entry) => SyncSettingUnsafeAccessors.Value(((SyncSetting)(entry.Entity))),
                string (IInternalEntry entry) => SyncSettingUnsafeAccessors.Value(((SyncSetting)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(value, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(value));
            value.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            value.TypeMapping = SqliteStringTypeMapping.Default;
            value.AddAnnotation("Relational:ColumnName", "Value");

            var key0 = runtimeEntityType.AddKey(
                new[] { key });
            runtimeEntityType.SetPrimaryKey(key0);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var key = runtimeEntityType.FindProperty("Key");
            var value = runtimeEntityType.FindProperty("Value");
            var key0 = runtimeEntityType.FindKey(new[] { key });
            key0.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNullableFactory<string, int>(key0));
            key0.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<string>(key0));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((SyncSetting)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string, string>((source.GetCurrentValue<string>(key) == null ? null : ((ValueComparer<string>)(((IProperty)key).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(key))), (source.GetCurrentValue<string>(value) == null ? null : ((ValueComparer<string>)(((IProperty)value).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(value))))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => Snapshot.Empty);
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((SyncSetting)(source.Entity));
                    return ((ISnapshot)(new Snapshot<string>((source.GetCurrentValue<string>(key) == null ? null : ((ValueComparer<string>)(((IProperty)key).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<string>(key))))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 2,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 2,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 0));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "SyncSetting");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
