<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Nivaes.DataTestGenerator.XUnit" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Orquestation\Nivaes.App.Rpc.AppHost\Nivaes.App.Rpc.AppHost.AppHost\Nivaes.App.Rpc.AppHost.AppHost.csproj" />
    <ProjectReference Include="..\Nivaes.App.Rpc.Sample.Shared\Nivaes.App.Rpc.Sample.Shared.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
		<Using Include="Shouldly" />
	</ItemGroup>

</Project>