<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(_CommonTargets)</TargetFrameworks>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsAotCompatible>true</IsAotCompatible>
		<!--<RunAOTAnalysis>true</RunAOTAnalysis>-->
		<!--<WarningsAsErrors>IL2CPP;IL3xxx</WarningsAsErrors>-->
		<OptimizationPreference>Speed</OptimizationPreference>
		<IsTrimmable>true</IsTrimmable>

		<InterceptorsNamespaces>$(InterceptorsNamespaces);Microsoft.EntityFrameworkCore.GeneratedInterceptors</InterceptorsNamespaces>
	</PropertyGroup>

	<PropertyGroup>
		<PackageId>Nivaes.App.Rpc.Client</PackageId>
		<Title>Nivaes.App.Rpc.Client</Title>

		<Product>Nivaes.App.Rpc.Client</Product>
		<Description>Nivaes.App.Rpc.Client.</Description>
		<PackageTags>Nivaes.App.Rpc.Client</PackageTags>
		<PackageReadmeFile>Readme.md</PackageReadmeFile>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.Net.Client" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tasks">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Nivaes.App.Rpc.Shared\Nivaes.App.Rpc.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Nivaes.App.Rpc.Sample.UnitTests" />
		<InternalsVisibleTo Include="Nivaes.App.Rpc.Client.Database.Tools" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Images\icon.png" Pack="true" PackagePath="icon.png" />
		<None Include="Docs\Readme.md" Pack="true" PackagePath="Readme.md" />
	</ItemGroup>

</Project>
