using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Nivaes.App.Rpc.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public class RegisterRpcDataModelsActionsGenerator : IIncrementalGenerator
{
    private record struct ConverterInfo(INamedTypeSymbol RpcModelType);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var converters = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetConverterType(ctx))
            .Where(static c => c is not null)!;

        var rootNamespace = context.AnalyzerConfigOptionsProvider
            .Select(static (options, _) =>
            {
                options.GlobalOptions.TryGetValue(
                    "build_property.RootNamespace",
                    out var ns);

                return ns;
            });

        context.RegisterSourceOutput(
            converters.Collect().Combine(rootNamespace),
            Generate);
    }

    private static ConverterInfo? GetConverterType(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol symbol)
            return null;

        // Ignorar clases abstractas y genéricas
        if (symbol.IsAbstract || symbol.IsGenericType)
            return null;

        var compilation = context.SemanticModel.Compilation;

        var viewInterface =
            compilation.GetTypeByMetadataName("Nivaes.App.Rpc.IRpcDataModel");

        if (viewInterface is null)
            return null;

        // Debe implementar ICrossView
        if (!symbol.AllInterfaces.Any(i =>
            SymbolEqualityComparer.Default.Equals(i, viewInterface)))
        {
            return null;
        }

        return new ConverterInfo(symbol);
    }

    private static void Generate(
        SourceProductionContext context,
        (ImmutableArray<ConverterInfo?> ressenterActions, string? rootNamespace) input)
    {
        var types = input.ressenterActions
            .Where(x => x != null)
            .Cast<ConverterInfo>()
            .GroupBy(x => x.RpcModelType)
            .Select(g => g.First())
            .OrderBy(x => x.RpcModelType.Name);

        var rootNamespace = string.IsNullOrWhiteSpace(input.rootNamespace) ? string.Empty : $"namespace {input.rootNamespace};";

        var sourceConverters = string.Join(Environment.NewLine,
            types.Select(type =>
                {
                    return $"RpcDataModelTypeContainerHelper.New<{type.RpcModelType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(),";
                }
            ));

        string sourceRegisterConverters = string.Empty;
        if (!string.IsNullOrWhiteSpace(sourceConverters))
        {
            sourceRegisterConverters = $@"
                    RpcDataModelTypeContainerHelper.RegisterRpcDataModels(new[]
                    {{
                       {sourceConverters}
                    }});";
        }

        var source = @$"// This file generated for Nivaes.App.Rpc.
            // <auto-generated/>
            using System;
            using Nivaes.App.Rpc;
            {rootNamespace}
            public static class GeneratedRegisterRpcDataModelsExtensions
            {{
                public static void RegisterRpcDataModelsActions()
                {{
                    {sourceRegisterConverters}
                }}
            }}
        ";

        context.AddSource(
            "GeneratedRegisterRpcDataModelsExtensions.g.cs",
            SourceText.From(source, Encoding.UTF8));
    }
}