<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-ios</TargetFramework>
    <OutputType>Exe</OutputType>
    <Nullable>enable</Nullable>
    <ImplicitUsings>true</ImplicitUsings>
    <SupportedOSPlatformVersion>13.0</SupportedOSPlatformVersion>

    <!--
      Enable full trimming in Release mode.
      To learn more, see: https://learn.microsoft.com/dotnet/core/deploying/trimming/trimming-options#trimming-granularity
    -->
    <TrimMode Condition="'$(Configuration)' == 'Release'">full</TrimMode>
  </PropertyGroup>

	<ItemGroup>
		<!--<PackageReference Include="Microsoft.EntityFrameworkCore.Tasks">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>-->

		<PackageReference Include="Nivaes.DataTestGenerator" />
	</ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\Nivaes.App.Rpc.Sample.Client\Nivaes.App.Rpc.Sample.Client.csproj" />
  </ItemGroup>
</Project>
