<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>$(_CommonTargets)</TargetFrameworks>
	  <AssemblyName>Nivaes.App.Rpc</AssemblyName>
	  <RootNamespace>Nivaes.App.Rpc</RootNamespace>
	  
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	  <IsAotCompatible>true</IsAotCompatible>
	  <!--<RunAOTAnalysis>true</RunAOTAnalysis>-->
	  <!--<WarningsAsErrors>IL2CPP;IL3xxx</WarningsAsErrors>-->
	  <OptimizationPreference>Speed</OptimizationPreference>
	  <IsTrimmable>true</IsTrimmable>
  </PropertyGroup>

	<PropertyGroup>
		<PackageId>Nivaes.App.Rpc</PackageId>
		<Title>Nivaes.App.Rpc</Title>

		<Product>Nivaes.App.Rpc</Product>
		<Description>Nivaes.App.Rpc.</Description>
		<PackageTags>Nivaes.App.Rpc</PackageTags>
		<PackageReadmeFile>Readme.md</PackageReadmeFile>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MemoryPack" />
    <PackageReference Include="Nivaes.Extensions" />
    <PackageReference Include="protobuf-net.Grpc" />
  </ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="Nivaes.App.Rpc.Client" />
		<InternalsVisibleTo Include="Nivaes.App.Rpc.AspNetCore.Server" />
		<InternalsVisibleTo Include="Nivaes.App.Rpc.Sample.Tests"/>
	</ItemGroup>

  <ItemGroup>
	  <ProjectReference Include="..\Nivaes.App.Rpc.SourceGenerator\Nivaes.App.Rpc.SourceGenerator.csproj">
		  <OutputItemType>Analyzer</OutputItemType>
		  <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		  <PrivateAssets>runtime; build; native; contentfiles; buildtransitive</PrivateAssets>
		  <IncludeAssets>analyzers</IncludeAssets>
		  <ExcludeAssets>runtime; build; native; contentfiles; buildtransitive</ExcludeAssets>
	  </ProjectReference>
  </ItemGroup>

</Project>
