// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Nivaes.App.RPC.Sample.Client.Database
{
    public partial class DatabaseContextModel
    {
        private DatabaseContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("e7784616-a30b-4dde-ba29-0c199ee22d70"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var userDataModel = UserDataModelEntityType.Create(this);

            UserDataModelEntityType.CreateAnnotations(userDataModel);

            AddAnnotation("ProductVersion", "10.0.8");
        }
    }
}
