// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Nivaes.App.RPC.Sample.Client;
using Nivaes.App.RPC.Sample.Client.Database;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(DatabaseContext), typeof(DatabaseContextModel))]
