// <auto-generated />
using System;
using System.Runtime.CompilerServices;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Nivaes.App.RPC.Sample.Client.Database
{
    public static class DataModelUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<TimeStampTicks>k__BackingField")]
        public static extern ref long TimeStampTicks(DataModel @this);
    }
}
