// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Update.Internal;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Nivaes.App.RPC.Sample.Client.Database
{
    public partial class DatabaseContextModel
    {
        private DatabaseContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("550ff267-5ae7-4d8a-a6b5-e53883ab0e42"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var userDataModel = UserDataModelEntityType.Create(this);

            UserDataModelEntityType.CreateAnnotations(userDataModel);

            AddAnnotation("ProductVersion", "10.0.11");
            AddRuntimeAnnotation("Relational:RelationalModelFactory", () => CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var userDataModel = FindEntityType("Nivaes.App.RPC.Sample.UserDataModel")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            userDataModel.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var nivaesAppRPCSampleUserDataModelTableBase = new TableBase("Nivaes.App.RPC.Sample.UserDataModel", null, relationalModel);
            var descriptionColumnBase = new ColumnBase<ColumnMappingBase>("Description", "TEXT", nivaesAppRPCSampleUserDataModelTableBase)
            {
                IsNullable = true
            };
            nivaesAppRPCSampleUserDataModelTableBase.Columns.Add("Description", descriptionColumnBase);
            var emailColumnBase = new ColumnBase<ColumnMappingBase>("Email", "TEXT", nivaesAppRPCSampleUserDataModelTableBase)
            {
                IsNullable = true
            };
            nivaesAppRPCSampleUserDataModelTableBase.Columns.Add("Email", emailColumnBase);
            var familyNameColumnBase = new ColumnBase<ColumnMappingBase>("FamilyName", "TEXT", nivaesAppRPCSampleUserDataModelTableBase);
            nivaesAppRPCSampleUserDataModelTableBase.Columns.Add("FamilyName", familyNameColumnBase);
            var givenNameColumnBase = new ColumnBase<ColumnMappingBase>("GivenName", "TEXT", nivaesAppRPCSampleUserDataModelTableBase);
            nivaesAppRPCSampleUserDataModelTableBase.Columns.Add("GivenName", givenNameColumnBase);
            var idUserColumnBase = new ColumnBase<ColumnMappingBase>("IdUser", "TEXT", nivaesAppRPCSampleUserDataModelTableBase);
            nivaesAppRPCSampleUserDataModelTableBase.Columns.Add("IdUser", idUserColumnBase);
            var identificationColumnBase = new ColumnBase<ColumnMappingBase>("Identification", "TEXT", nivaesAppRPCSampleUserDataModelTableBase);
            nivaesAppRPCSampleUserDataModelTableBase.Columns.Add("Identification", identificationColumnBase);
            var nameColumnBase = new ColumnBase<ColumnMappingBase>("Name", "TEXT", nivaesAppRPCSampleUserDataModelTableBase);
            nivaesAppRPCSampleUserDataModelTableBase.Columns.Add("Name", nameColumnBase);
            var phoneNumberColumnBase = new ColumnBase<ColumnMappingBase>("PhoneNumber", "TEXT", nivaesAppRPCSampleUserDataModelTableBase)
            {
                IsNullable = true
            };
            nivaesAppRPCSampleUserDataModelTableBase.Columns.Add("PhoneNumber", phoneNumberColumnBase);
            var timeStampColumnBase = new ColumnBase<ColumnMappingBase>("TimeStamp", "TEXT", nivaesAppRPCSampleUserDataModelTableBase);
            nivaesAppRPCSampleUserDataModelTableBase.Columns.Add("TimeStamp", timeStampColumnBase);
            var timeStampTicksColumnBase = new ColumnBase<ColumnMappingBase>("TimeStampTicks", "INTEGER", nivaesAppRPCSampleUserDataModelTableBase);
            nivaesAppRPCSampleUserDataModelTableBase.Columns.Add("TimeStampTicks", timeStampTicksColumnBase);
            relationalModel.DefaultTables.Add("Nivaes.App.RPC.Sample.UserDataModel", nivaesAppRPCSampleUserDataModelTableBase);
            var nivaesAppRPCSampleUserDataModelMappingBase = new TableMappingBase<ColumnMappingBase>(userDataModel, nivaesAppRPCSampleUserDataModelTableBase, null);
            nivaesAppRPCSampleUserDataModelTableBase.AddTypeMapping(nivaesAppRPCSampleUserDataModelMappingBase, false);
            defaultTableMappings.Add(nivaesAppRPCSampleUserDataModelMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idUserColumnBase, userDataModel.FindProperty("IdUser")!, nivaesAppRPCSampleUserDataModelMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)descriptionColumnBase, userDataModel.FindProperty("Description")!, nivaesAppRPCSampleUserDataModelMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)emailColumnBase, userDataModel.FindProperty("Email")!, nivaesAppRPCSampleUserDataModelMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)familyNameColumnBase, userDataModel.FindProperty("FamilyName")!, nivaesAppRPCSampleUserDataModelMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)givenNameColumnBase, userDataModel.FindProperty("GivenName")!, nivaesAppRPCSampleUserDataModelMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)identificationColumnBase, userDataModel.FindProperty("Identification")!, nivaesAppRPCSampleUserDataModelMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nameColumnBase, userDataModel.FindProperty("Name")!, nivaesAppRPCSampleUserDataModelMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)phoneNumberColumnBase, userDataModel.FindProperty("PhoneNumber")!, nivaesAppRPCSampleUserDataModelMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)timeStampColumnBase, userDataModel.FindProperty("TimeStamp")!, nivaesAppRPCSampleUserDataModelMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)timeStampTicksColumnBase, userDataModel.FindProperty("TimeStampTicks")!, nivaesAppRPCSampleUserDataModelMappingBase);

            var tableMappings = new List<TableMapping>();
            userDataModel.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var usersTable = new Table("Users", null, relationalModel);
            var idUserColumn = new Column("IdUser", "TEXT", usersTable);
            usersTable.Columns.Add("IdUser", idUserColumn);
            idUserColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<Guid>(idUserColumn);
            var descriptionColumn = new Column("Description", "TEXT", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("Description", descriptionColumn);
            descriptionColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(descriptionColumn);
            var emailColumn = new Column("Email", "TEXT", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("Email", emailColumn);
            emailColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(emailColumn);
            var familyNameColumn = new Column("FamilyName", "TEXT", usersTable);
            usersTable.Columns.Add("FamilyName", familyNameColumn);
            familyNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(familyNameColumn);
            var givenNameColumn = new Column("GivenName", "TEXT", usersTable);
            usersTable.Columns.Add("GivenName", givenNameColumn);
            givenNameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(givenNameColumn);
            var identificationColumn = new Column("Identification", "TEXT", usersTable);
            usersTable.Columns.Add("Identification", identificationColumn);
            identificationColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(identificationColumn);
            var nameColumn = new Column("Name", "TEXT", usersTable);
            usersTable.Columns.Add("Name", nameColumn);
            nameColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(nameColumn);
            var phoneNumberColumn = new Column("PhoneNumber", "TEXT", usersTable)
            {
                IsNullable = true
            };
            usersTable.Columns.Add("PhoneNumber", phoneNumberColumn);
            phoneNumberColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<string>(phoneNumberColumn);
            var timeStampColumn = new Column("TimeStamp", "TEXT", usersTable);
            usersTable.Columns.Add("TimeStamp", timeStampColumn);
            timeStampColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<DateTime>(timeStampColumn);
            var timeStampTicksColumn = new Column("TimeStampTicks", "INTEGER", usersTable);
            usersTable.Columns.Add("TimeStampTicks", timeStampTicksColumn);
            timeStampTicksColumn.Accessors = ColumnAccessorsFactory.CreateGeneric<long>(timeStampTicksColumn);
            relationalModel.Tables.Add(("Users", null), usersTable);
            var usersTableMapping = new TableMapping(userDataModel, usersTable, null);
            usersTable.AddTypeMapping(usersTableMapping, false);
            tableMappings.Add(usersTableMapping);
            RelationalModel.CreateColumnMapping(idUserColumn, userDataModel.FindProperty("IdUser")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(descriptionColumn, userDataModel.FindProperty("Description")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(emailColumn, userDataModel.FindProperty("Email")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(familyNameColumn, userDataModel.FindProperty("FamilyName")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(givenNameColumn, userDataModel.FindProperty("GivenName")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(identificationColumn, userDataModel.FindProperty("Identification")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(nameColumn, userDataModel.FindProperty("Name")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(phoneNumberColumn, userDataModel.FindProperty("PhoneNumber")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(timeStampColumn, userDataModel.FindProperty("TimeStamp")!, usersTableMapping);
            RelationalModel.CreateColumnMapping(timeStampTicksColumn, userDataModel.FindProperty("TimeStampTicks")!, usersTableMapping);
            var pK_Users = new UniqueConstraint("PK_Users", usersTable, new[] { idUserColumn });
            usersTable.PrimaryKey = pK_Users;
            pK_Users.SetRowKeyValueFactory(new SimpleRowKeyValueFactory<Guid>(pK_Users));
            var pK_UsersKey = RelationalModel.GetKey(this,
                "Nivaes.App.RPC.Sample.UserDataModel",
                new[] { "IdUser" });
            pK_Users.MappedKeys.Add(pK_UsersKey);
            RelationalModel.GetOrCreateUniqueConstraints(pK_UsersKey).Add(pK_Users);
            usersTable.UniqueConstraints.Add("PK_Users", pK_Users);
            var iX_Users_FamilyName = new TableIndex(
            "IX_Users_FamilyName", usersTable, new[] { familyNameColumn }, false);
            iX_Users_FamilyName.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_Users_FamilyName));
            var iX_Users_FamilyNameIx = RelationalModel.GetIndex(this,
                "Nivaes.App.RPC.Sample.UserDataModel",
                new[] { "FamilyName" });
            iX_Users_FamilyName.MappedIndexes.Add(iX_Users_FamilyNameIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Users_FamilyNameIx).Add(iX_Users_FamilyName);
            usersTable.Indexes.Add("IX_Users_FamilyName", iX_Users_FamilyName);
            var iX_Users_GivenName = new TableIndex(
            "IX_Users_GivenName", usersTable, new[] { givenNameColumn }, false);
            iX_Users_GivenName.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_Users_GivenName));
            var iX_Users_GivenNameIx = RelationalModel.GetIndex(this,
                "Nivaes.App.RPC.Sample.UserDataModel",
                new[] { "GivenName" });
            iX_Users_GivenName.MappedIndexes.Add(iX_Users_GivenNameIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Users_GivenNameIx).Add(iX_Users_GivenName);
            usersTable.Indexes.Add("IX_Users_GivenName", iX_Users_GivenName);
            var iX_Users_Name = new TableIndex(
            "IX_Users_Name", usersTable, new[] { nameColumn }, false);
            iX_Users_Name.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<string>(iX_Users_Name));
            var iX_Users_NameIx = RelationalModel.GetIndex(this,
                "Nivaes.App.RPC.Sample.UserDataModel",
                new[] { "Name" });
            iX_Users_Name.MappedIndexes.Add(iX_Users_NameIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Users_NameIx).Add(iX_Users_Name);
            usersTable.Indexes.Add("IX_Users_Name", iX_Users_Name);
            var iX_Users_TimeStampTicks = new TableIndex(
            "IX_Users_TimeStampTicks", usersTable, new[] { timeStampTicksColumn }, false);
            iX_Users_TimeStampTicks.SetRowIndexValueFactory(new SimpleRowIndexValueFactory<long>(iX_Users_TimeStampTicks));
            var iX_Users_TimeStampTicksIx = RelationalModel.GetIndex(this,
                "Nivaes.App.RPC.Sample.UserDataModel",
                new[] { "TimeStampTicks" });
            iX_Users_TimeStampTicks.MappedIndexes.Add(iX_Users_TimeStampTicksIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Users_TimeStampTicksIx).Add(iX_Users_TimeStampTicks);
            usersTable.Indexes.Add("IX_Users_TimeStampTicks", iX_Users_TimeStampTicks);
            return relationalModel.MakeReadOnly();
        }
    }
}
