// <auto-generated />
using System;
using System.Runtime.CompilerServices;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Nivaes.App.RPC.Sample.Client.Database
{
    public static class UserDataModelUnsafeAccessors
    {
        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<IdUser>k__BackingField")]
        public static extern ref Guid IdUser(UserDataModel @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Description>k__BackingField")]
        public static extern ref string Description(UserDataModel @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Email>k__BackingField")]
        public static extern ref string Email(UserDataModel @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<FamilyName>k__BackingField")]
        public static extern ref string FamilyName(UserDataModel @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<GivenName>k__BackingField")]
        public static extern ref string GivenName(UserDataModel @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Identification>k__BackingField")]
        public static extern ref string Identification(UserDataModel @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<Name>k__BackingField")]
        public static extern ref string Name(UserDataModel @this);

        [UnsafeAccessor(UnsafeAccessorKind.Field, Name = "<PhoneNumber>k__BackingField")]
        public static extern ref string PhoneNumber(UserDataModel @this);
    }
}
