// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.ChangeTracking.Internal;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Nivaes.App.RPC.Sample.Client.Database
{
    [EntityFrameworkInternal]
    public partial class UserDataModelEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "Nivaes.App.RPC.Sample.UserDataModel",
                typeof(UserDataModel),
                baseEntityType,
                propertyCount: 10,
                unnamedIndexCount: 4,
                keyCount: 1);

            var idUser = runtimeEntityType.AddProperty(
                "IdUser",
                typeof(Guid),
                propertyInfo: typeof(UserDataModel).GetProperty("IdUser", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserDataModel).GetField("<IdUser>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: new Guid("00000000-0000-0000-0000-000000000000"));
            idUser.SetGetter(
                Guid (UserDataModel instance) => UserDataModelUnsafeAccessors.IdUser(instance),
                bool (UserDataModel instance) => UserDataModelUnsafeAccessors.IdUser(instance) == new Guid("00000000-0000-0000-0000-000000000000"));
            idUser.SetSetter(
                UserDataModel (UserDataModel instance, Guid value) =>
                {
                    UserDataModelUnsafeAccessors.IdUser(instance) = value;
                    return instance;
                });
            idUser.SetMaterializationSetter(
                UserDataModel (UserDataModel instance, Guid value) =>
                {
                    UserDataModelUnsafeAccessors.IdUser(instance) = value;
                    return instance;
                });
            idUser.SetAccessors(
                Guid (IInternalEntry entry) => (entry.FlaggedAsStoreGenerated(0) ? entry.ReadStoreGeneratedValue<Guid>(0) : (entry.FlaggedAsTemporary(0) && UserDataModelUnsafeAccessors.IdUser(((UserDataModel)(entry.Entity))) == new Guid("00000000-0000-0000-0000-000000000000") ? entry.ReadTemporaryValue<Guid>(0) : UserDataModelUnsafeAccessors.IdUser(((UserDataModel)(entry.Entity))))),
                Guid (IInternalEntry entry) => UserDataModelUnsafeAccessors.IdUser(((UserDataModel)(entry.Entity))),
                Guid (IInternalEntry entry) => entry.ReadOriginalValue<Guid>(idUser, 0),
                Guid (IInternalEntry entry) => ((InternalEntityEntry)entry).ReadRelationshipSnapshotValue<Guid>(idUser, 0));
            idUser.SetPropertyIndexes(
                index: 0,
                originalValueIndex: 0,
                shadowIndex: -1,
                relationshipIndex: 0,
                storeGenerationIndex: 0);
            idUser.TypeMapping = SqliteGuidTypeMapping.Default;
            idUser.SetCurrentValueComparer(new EntryCurrentValueComparer<Guid>(idUser));
            idUser.AddAnnotation("Relational:ColumnName", "IdUser");

            var description = runtimeEntityType.AddProperty(
                "Description",
                typeof(string),
                propertyInfo: typeof(UserDataModel).GetProperty("Description", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserDataModel).GetField("<Description>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            description.SetGetter(
                string (UserDataModel instance) => UserDataModelUnsafeAccessors.Description(instance),
                bool (UserDataModel instance) => UserDataModelUnsafeAccessors.Description(instance) == null);
            description.SetSetter(
                UserDataModel (UserDataModel instance, string value) =>
                {
                    UserDataModelUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetMaterializationSetter(
                UserDataModel (UserDataModel instance, string value) =>
                {
                    UserDataModelUnsafeAccessors.Description(instance) = value;
                    return instance;
                });
            description.SetAccessors(
                string (IInternalEntry entry) => UserDataModelUnsafeAccessors.Description(((UserDataModel)(entry.Entity))),
                string (IInternalEntry entry) => UserDataModelUnsafeAccessors.Description(((UserDataModel)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(description, 1),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(description));
            description.SetPropertyIndexes(
                index: 1,
                originalValueIndex: 1,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            description.TypeMapping = SqliteStringTypeMapping.Default;

            var email = runtimeEntityType.AddProperty(
                "Email",
                typeof(string),
                propertyInfo: typeof(UserDataModel).GetProperty("Email", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserDataModel).GetField("<Email>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            email.SetGetter(
                string (UserDataModel instance) => UserDataModelUnsafeAccessors.Email(instance),
                bool (UserDataModel instance) => UserDataModelUnsafeAccessors.Email(instance) == null);
            email.SetSetter(
                UserDataModel (UserDataModel instance, string value) =>
                {
                    UserDataModelUnsafeAccessors.Email(instance) = value;
                    return instance;
                });
            email.SetMaterializationSetter(
                UserDataModel (UserDataModel instance, string value) =>
                {
                    UserDataModelUnsafeAccessors.Email(instance) = value;
                    return instance;
                });
            email.SetAccessors(
                string (IInternalEntry entry) => UserDataModelUnsafeAccessors.Email(((UserDataModel)(entry.Entity))),
                string (IInternalEntry entry) => UserDataModelUnsafeAccessors.Email(((UserDataModel)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(email, 2),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(email));
            email.SetPropertyIndexes(
                index: 2,
                originalValueIndex: 2,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            email.TypeMapping = SqliteStringTypeMapping.Default;
            email.AddAnnotation("Relational:ColumnName", "Email");

            var familyName = runtimeEntityType.AddProperty(
                "FamilyName",
                typeof(string),
                propertyInfo: typeof(UserDataModel).GetProperty("FamilyName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserDataModel).GetField("<FamilyName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            familyName.SetGetter(
                string (UserDataModel instance) => UserDataModelUnsafeAccessors.FamilyName(instance),
                bool (UserDataModel instance) => UserDataModelUnsafeAccessors.FamilyName(instance) == null);
            familyName.SetSetter(
                UserDataModel (UserDataModel instance, string value) =>
                {
                    UserDataModelUnsafeAccessors.FamilyName(instance) = value;
                    return instance;
                });
            familyName.SetMaterializationSetter(
                UserDataModel (UserDataModel instance, string value) =>
                {
                    UserDataModelUnsafeAccessors.FamilyName(instance) = value;
                    return instance;
                });
            familyName.SetAccessors(
                string (IInternalEntry entry) => UserDataModelUnsafeAccessors.FamilyName(((UserDataModel)(entry.Entity))),
                string (IInternalEntry entry) => UserDataModelUnsafeAccessors.FamilyName(((UserDataModel)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(familyName, 3),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(familyName));
            familyName.SetPropertyIndexes(
                index: 3,
                originalValueIndex: 3,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            familyName.TypeMapping = SqliteStringTypeMapping.Default;
            familyName.AddAnnotation("Relational:ColumnName", "FamilyName");

            var givenName = runtimeEntityType.AddProperty(
                "GivenName",
                typeof(string),
                propertyInfo: typeof(UserDataModel).GetProperty("GivenName", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserDataModel).GetField("<GivenName>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            givenName.SetGetter(
                string (UserDataModel instance) => UserDataModelUnsafeAccessors.GivenName(instance),
                bool (UserDataModel instance) => UserDataModelUnsafeAccessors.GivenName(instance) == null);
            givenName.SetSetter(
                UserDataModel (UserDataModel instance, string value) =>
                {
                    UserDataModelUnsafeAccessors.GivenName(instance) = value;
                    return instance;
                });
            givenName.SetMaterializationSetter(
                UserDataModel (UserDataModel instance, string value) =>
                {
                    UserDataModelUnsafeAccessors.GivenName(instance) = value;
                    return instance;
                });
            givenName.SetAccessors(
                string (IInternalEntry entry) => UserDataModelUnsafeAccessors.GivenName(((UserDataModel)(entry.Entity))),
                string (IInternalEntry entry) => UserDataModelUnsafeAccessors.GivenName(((UserDataModel)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(givenName, 4),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(givenName));
            givenName.SetPropertyIndexes(
                index: 4,
                originalValueIndex: 4,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            givenName.TypeMapping = SqliteStringTypeMapping.Default;
            givenName.AddAnnotation("Relational:ColumnName", "GivenName");

            var identification = runtimeEntityType.AddProperty(
                "Identification",
                typeof(string),
                propertyInfo: typeof(UserDataModel).GetProperty("Identification", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserDataModel).GetField("<Identification>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            identification.SetGetter(
                string (UserDataModel instance) => UserDataModelUnsafeAccessors.Identification(instance),
                bool (UserDataModel instance) => UserDataModelUnsafeAccessors.Identification(instance) == null);
            identification.SetSetter(
                UserDataModel (UserDataModel instance, string value) =>
                {
                    UserDataModelUnsafeAccessors.Identification(instance) = value;
                    return instance;
                });
            identification.SetMaterializationSetter(
                UserDataModel (UserDataModel instance, string value) =>
                {
                    UserDataModelUnsafeAccessors.Identification(instance) = value;
                    return instance;
                });
            identification.SetAccessors(
                string (IInternalEntry entry) => UserDataModelUnsafeAccessors.Identification(((UserDataModel)(entry.Entity))),
                string (IInternalEntry entry) => UserDataModelUnsafeAccessors.Identification(((UserDataModel)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(identification, 5),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(identification));
            identification.SetPropertyIndexes(
                index: 5,
                originalValueIndex: 5,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            identification.TypeMapping = SqliteStringTypeMapping.Default;
            identification.AddAnnotation("Relational:ColumnName", "Identification");

            var name = runtimeEntityType.AddProperty(
                "Name",
                typeof(string),
                propertyInfo: typeof(UserDataModel).GetProperty("Name", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserDataModel).GetField("<Name>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            name.SetGetter(
                string (UserDataModel instance) => UserDataModelUnsafeAccessors.Name(instance),
                bool (UserDataModel instance) => UserDataModelUnsafeAccessors.Name(instance) == null);
            name.SetSetter(
                UserDataModel (UserDataModel instance, string value) =>
                {
                    UserDataModelUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetMaterializationSetter(
                UserDataModel (UserDataModel instance, string value) =>
                {
                    UserDataModelUnsafeAccessors.Name(instance) = value;
                    return instance;
                });
            name.SetAccessors(
                string (IInternalEntry entry) => UserDataModelUnsafeAccessors.Name(((UserDataModel)(entry.Entity))),
                string (IInternalEntry entry) => UserDataModelUnsafeAccessors.Name(((UserDataModel)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(name, 6),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(name));
            name.SetPropertyIndexes(
                index: 6,
                originalValueIndex: 6,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            name.TypeMapping = SqliteStringTypeMapping.Default;
            name.AddAnnotation("Relational:ColumnName", "Name");

            var phoneNumber = runtimeEntityType.AddProperty(
                "PhoneNumber",
                typeof(string),
                propertyInfo: typeof(UserDataModel).GetProperty("PhoneNumber", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(UserDataModel).GetField("<PhoneNumber>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            phoneNumber.SetGetter(
                string (UserDataModel instance) => UserDataModelUnsafeAccessors.PhoneNumber(instance),
                bool (UserDataModel instance) => UserDataModelUnsafeAccessors.PhoneNumber(instance) == null);
            phoneNumber.SetSetter(
                UserDataModel (UserDataModel instance, string value) =>
                {
                    UserDataModelUnsafeAccessors.PhoneNumber(instance) = value;
                    return instance;
                });
            phoneNumber.SetMaterializationSetter(
                UserDataModel (UserDataModel instance, string value) =>
                {
                    UserDataModelUnsafeAccessors.PhoneNumber(instance) = value;
                    return instance;
                });
            phoneNumber.SetAccessors(
                string (IInternalEntry entry) => UserDataModelUnsafeAccessors.PhoneNumber(((UserDataModel)(entry.Entity))),
                string (IInternalEntry entry) => UserDataModelUnsafeAccessors.PhoneNumber(((UserDataModel)(entry.Entity))),
                string (IInternalEntry entry) => entry.ReadOriginalValue<string>(phoneNumber, 7),
                string (IInternalEntry entry) => entry.GetCurrentValue<string>(phoneNumber));
            phoneNumber.SetPropertyIndexes(
                index: 7,
                originalValueIndex: 7,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            phoneNumber.TypeMapping = SqliteStringTypeMapping.Default;
            phoneNumber.AddAnnotation("Relational:ColumnName", "PhoneNumber");

            var timeStamp = runtimeEntityType.AddProperty(
                "TimeStamp",
                typeof(DateTime),
                propertyInfo: typeof(DataModel).GetProperty("TimeStamp", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            timeStamp.SetGetter(
                DateTime (UserDataModel instance) => instance.TimeStamp,
                bool (UserDataModel instance) => instance.TimeStamp == default(DateTime));
            timeStamp.SetSetter(
                UserDataModel (UserDataModel instance, DateTime value) =>
                {
                    instance.TimeStamp = value;
                    return instance;
                });
            timeStamp.SetMaterializationSetter(
                UserDataModel (UserDataModel instance, DateTime value) =>
                {
                    instance.TimeStamp = value;
                    return instance;
                });
            timeStamp.SetAccessors(
                DateTime (IInternalEntry entry) => ((UserDataModel)(entry.Entity)).TimeStamp,
                DateTime (IInternalEntry entry) => ((UserDataModel)(entry.Entity)).TimeStamp,
                DateTime (IInternalEntry entry) => entry.ReadOriginalValue<DateTime>(timeStamp, 8),
                DateTime (IInternalEntry entry) => entry.GetCurrentValue<DateTime>(timeStamp));
            timeStamp.SetPropertyIndexes(
                index: 8,
                originalValueIndex: 8,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            timeStamp.TypeMapping = SqliteDateTimeTypeMapping.Default;

            var timeStampTicks = runtimeEntityType.AddProperty(
                "TimeStampTicks",
                typeof(long),
                propertyInfo: typeof(DataModel).GetProperty("TimeStampTicks", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(DataModel).GetField("<TimeStampTicks>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0L);
            timeStampTicks.SetGetter(
                long (UserDataModel instance) => DataModelUnsafeAccessors.TimeStampTicks(instance),
                bool (UserDataModel instance) => DataModelUnsafeAccessors.TimeStampTicks(instance) == 0L);
            timeStampTicks.SetSetter(
                UserDataModel (UserDataModel instance, long value) =>
                {
                    DataModelUnsafeAccessors.TimeStampTicks(instance) = value;
                    return instance;
                });
            timeStampTicks.SetMaterializationSetter(
                UserDataModel (UserDataModel instance, long value) =>
                {
                    DataModelUnsafeAccessors.TimeStampTicks(instance) = value;
                    return instance;
                });
            timeStampTicks.SetAccessors(
                long (IInternalEntry entry) => DataModelUnsafeAccessors.TimeStampTicks(((UserDataModel)(entry.Entity))),
                long (IInternalEntry entry) => DataModelUnsafeAccessors.TimeStampTicks(((UserDataModel)(entry.Entity))),
                long (IInternalEntry entry) => entry.ReadOriginalValue<long>(timeStampTicks, 9),
                long (IInternalEntry entry) => entry.GetCurrentValue<long>(timeStampTicks));
            timeStampTicks.SetPropertyIndexes(
                index: 9,
                originalValueIndex: 9,
                shadowIndex: -1,
                relationshipIndex: -1,
                storeGenerationIndex: -1);
            timeStampTicks.TypeMapping = LongTypeMapping.Default.Clone(
                comparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                keyComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                providerValueComparer: new ValueComparer<long>(
                    bool (long v1, long v2) => v1 == v2,
                    int (long v) => ((object)v).GetHashCode(),
                    long (long v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "INTEGER"));
            timeStampTicks.AddAnnotation("Relational:ColumnName", "TimeStampTicks");

            var key = runtimeEntityType.AddKey(
                new[] { idUser });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { familyName });

            var index0 = runtimeEntityType.AddIndex(
                new[] { givenName });

            var index1 = runtimeEntityType.AddIndex(
                new[] { name });

            var index2 = runtimeEntityType.AddIndex(
                new[] { timeStampTicks });

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            var idUser = runtimeEntityType.FindProperty("IdUser");
            var description = runtimeEntityType.FindProperty("Description");
            var email = runtimeEntityType.FindProperty("Email");
            var familyName = runtimeEntityType.FindProperty("FamilyName");
            var givenName = runtimeEntityType.FindProperty("GivenName");
            var identification = runtimeEntityType.FindProperty("Identification");
            var name = runtimeEntityType.FindProperty("Name");
            var phoneNumber = runtimeEntityType.FindProperty("PhoneNumber");
            var timeStamp = runtimeEntityType.FindProperty("TimeStamp");
            var timeStampTicks = runtimeEntityType.FindProperty("TimeStampTicks");
            var key = runtimeEntityType.FindKey(new[] { idUser });
            key.SetPrincipalKeyValueFactory(KeyValueFactoryFactory.CreateSimpleNonNullableFactory<Guid>(key));
            key.SetIdentityMapFactory(IdentityMapFactoryFactory.CreateFactory<Guid>(key));
            runtimeEntityType.SetOriginalValuesFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((UserDataModel)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid, string, string, string, string, string, string, string, DateTime, long>(((ValueComparer<Guid>)(((IProperty)idUser).GetValueComparer())).Snapshot(source.GetCurrentValue<Guid>(idUser)), (source.GetCurrentValue<string>(description) == null ? null : ((ValueComparer<string>)(((IProperty)description).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(description))), (source.GetCurrentValue<string>(email) == null ? null : ((ValueComparer<string>)(((IProperty)email).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(email))), (source.GetCurrentValue<string>(familyName) == null ? null : ((ValueComparer<string>)(((IProperty)familyName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(familyName))), (source.GetCurrentValue<string>(givenName) == null ? null : ((ValueComparer<string>)(((IProperty)givenName).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(givenName))), (source.GetCurrentValue<string>(identification) == null ? null : ((ValueComparer<string>)(((IProperty)identification).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(identification))), (source.GetCurrentValue<string>(name) == null ? null : ((ValueComparer<string>)(((IProperty)name).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(name))), (source.GetCurrentValue<string>(phoneNumber) == null ? null : ((ValueComparer<string>)(((IProperty)phoneNumber).GetValueComparer())).Snapshot(source.GetCurrentValue<string>(phoneNumber))), ((ValueComparer<DateTime>)(((IProperty)timeStamp).GetValueComparer())).Snapshot(source.GetCurrentValue<DateTime>(timeStamp)), ((ValueComparer<long>)(((IProperty)timeStampTicks).GetValueComparer())).Snapshot(source.GetCurrentValue<long>(timeStampTicks)))));
                });
            runtimeEntityType.SetStoreGeneratedValuesFactory(
                ISnapshot () => ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)idUser).GetValueComparer())).Snapshot(default(Guid))))));
            runtimeEntityType.SetTemporaryValuesFactory(
                ISnapshot (IInternalEntry source) => ((ISnapshot)(new Snapshot<Guid>(default(Guid)))));
            runtimeEntityType.SetShadowValuesFactory(
                ISnapshot (IDictionary<string, object> source) => Snapshot.Empty);
            runtimeEntityType.SetEmptyShadowValuesFactory(
                ISnapshot () => Snapshot.Empty);
            runtimeEntityType.SetRelationshipSnapshotFactory(
                ISnapshot (IInternalEntry source) =>
                {
                    var structuralType = ((UserDataModel)(source.Entity));
                    return ((ISnapshot)(new Snapshot<Guid>(((ValueComparer<Guid>)(((IProperty)idUser).GetKeyValueComparer())).Snapshot(source.GetCurrentValue<Guid>(idUser)))));
                });
            runtimeEntityType.SetCounts(new PropertyCounts(
                propertyCount: 10,
                navigationCount: 0,
                complexPropertyCount: 0,
                complexCollectionCount: 0,
                originalValueCount: 10,
                shadowCount: 0,
                relationshipCount: 1,
                storeGeneratedCount: 1));
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Users");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
