<Project Sdk="Aspire.AppHost.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	  <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>52085e4a-f6d8-4773-ba98-2a61b8a3cc26</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.MongoDB" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.MongoDB.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Samples\Nivaes.App.Rpc.Sample.Console.Read\Nivaes.App.Rpc.Sample.Console.Read.csproj" />
    <ProjectReference Include="..\..\..\Samples\Nivaes.App.Rpc.Sample.Console\Nivaes.App.Rpc.Sample.Console.csproj" />
    <ProjectReference Include="..\..\..\Samples\Nivaes.App.RPC.Sample.Server\Nivaes.App.Rpc.Sample.Server.csproj" />
  </ItemGroup>

</Project>
