<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nivaes.App.RPC.Sample.Shared\Nivaes.App.RPC.Sample.Shared.csproj" />
  </ItemGroup>

</Project>
