<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFrameworks>$(_CommonTargets)</TargetFrameworks>
	  
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Docs\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.MongoDB.Driver" />
    <PackageReference Include="Grpc.AspNetCore.Server" />
    <PackageReference Include="Grpc.AspNetCore.Web" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Nivaes.App.Rpc.Shared\Nivaes.App.Rpc.Shared.csproj" />
  </ItemGroup>

</Project>
