name: SyncInfo

on:
  workflow_dispatch:

jobs:
  SyncInfo:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - ubuntu-latest-arm
        - ubuntu-slim  
        - windows-latest
        - windows-latest-arm
        - macos-latest
        - macos-latest-intel
        - xcode-latest

    runs-on:  ${{ matrix.os }}

    steps:
      - name: System information
        shell: bash
        run: |
          echo "=== CPU ==="
          nproc
          lscpu
          echo "=== MEMORY ==="
          free -h
          echo "=== DISK ==="
          df -h
          echo "=== DOCKER ==="
          docker info